### ISSUE TITLE
Constant action policy

### ISSUE THREAD

**Issue by MaximeBouton** [JuliaPOMDP/POMDPPolicies.jl#3]
It would be nice to have a default implementation of a policy that would always return the same action. 
Something like that:
```julia
struct ConstantActionPolicy
    a
end

action(policy::ConstantActionPolicy, b) = a
```

**Comment by zsunberg** [comment]
I typically do this with e.g. FunctionPolicy(s->:up), but yeah I think it
would be ok to have one.

When I first read that I thought it was a constant (but potentially
different) action for each state. Maybe SingleActionPolicy would be a
better name.

(sent from phone)

**Comment by MaximeBouton** [comment]
SingleActionPolicy is a better name. 
The `FunctionPolicy` version is quite simple, I am hesitant to adding a new type then.

**Comment by rejuvyesh** [comment]
Yeah. `FunctionPolicy` should be enough.
