### ISSUE TITLE
Minor version release for CrossEntropyMethod.jl dependency

### ISSUE THREAD

**Issue by mossr** [JuliaPOMDP/POMDPPolicies.jl#30]
@MaximeBouton could you please release a version update into General so I can submit [CrossEntropyMethod.jl](https://github.com/sisl/CrossEntropyMethod.jl) to General?

**Comment by MaximeBouton** [comment]
https://github.com/JuliaRegistries/General/pull/21605

**Comment by mossr** [comment]
Thanks for all the dependency help! CrossEntropyMethod is now in General.
