### ISSUE TITLE
please tag for Distributions 0.25 compat

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaPOMDP/POMDPPolicies.jl#43]
POMDPPolicies.jl is currently causing downgrade catastrophes for me because of Distributions 0.25.

Something a bit peculiar seems to be happening with tagging as the registry lists this as at 0.4.1 but there is no github tag for that version.  Note that the latest tag in the registry is definitely not allowing distributions 0.25, see [here](https://github.com/JuliaRegistries/General/blob/master/P/POMDPPolicies/Compat.toml#L47).  Perhaps the simplest solution would be to tag an 0.4.2?

**Comment by rejuvyesh** [comment]
Waiting on https://github.com/JuliaRegistries/General/pull/48097.
